gamebit/main/routes.py
from flask import Flask, Blueprint, render_template
from gamebit.models import User

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
  return render_template("home/home.html", title="Home")

@main.route("/about")
def about():
  users = User.query.all()
  return render_template("home/about.html", title="About us", users=users)

@main.route("/about/rules")
def rules():
  return render_template("home/rules.html", title="Rules")

gamebit/memes/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, flash, 
                   redirect, url_for, abort, current_app)
from gamebit.models import Meme
from flask_login import current_user
from gamebit import db
from gamebit.memes.forms import MemeForm
from gamebit.users.utils import save_picture_all

memes = Blueprint("memes", __name__)

#meme routes
@memes.route("/memes", methods=["GET", "POST"])
def meme_list():
  page = request.args.get("page", 1, type=int)
  memes = Meme.query.order_by(
      Meme.date_posted.desc()).paginate(page=page, per_page=10)
  return render_template("memes/meme_list.html", title="Memes", memes=memes)


@memes.route("/memes/mem-<meme_id>", methods=["GET", "POST"])
def full_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  return render_template("memes/full_meme.html", title="{}".format(meme.caption), meme=meme)


@memes.route("/memes/new", methods=["GET", "POST"])
def new_meme():
  if current_user.is_authenticated:
    form = MemeForm()
    if form.validate_on_submit():
      if form.meme.data:
        path = current_app.config["MEME_PATH"]
        try:
          if not os.path.exists(path):
            os.mkdir(path)
        except OSError:
          print("Couldn't create the directory {}".format(path))
        posted_meme = save_picture_all(form.meme.data, path, (1280, 720))
        meme = Meme(meme=posted_meme, caption=form.caption.data, author=current_user)
        db.session.add(meme)
      db.session.commit()
      flash(f"Your meme has been submitted!", "success")
      return redirect(url_for("memes.meme_list"))
  else:
    abort(403)
  return render_template("memes/new_meme.html", title="Upload a Meme", form=form, legend="Make someone laugh!")


@memes.route("/memes/delete/mem-<meme_id>", methods=["GET", "POST"])
def delete_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  if current_user == meme.author: 
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  elif current_user.role == "Admin":
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  else:
    abort(403)

gamebit/reviews/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, abort, flash, 
                   redirect, url_for, current_app)
from gamebit.models import Review, User, Meme, Picture
from flask_login import current_user, login_required
from gamebit import db
from gamebit.reviews.forms import ReviewForm, UpdateReviewForm, PictureReviewForm
from gamebit.users.utils import save_picture_all

reviews = Blueprint("reviews", __name__)

#Review routes
@reviews.route("/reviews")
def review_list():
  page = request.args.get("page", 1, type=int)
  reviews = Review.query.order_by(
      Review.date_posted.desc()).paginate(page=page, per_page=4)
  return render_template("reviews/review_list.html", title="Reviews", reviews=reviews)


@reviews.route("/reviews/summary/<string:username>")
def user_review(username):
  user = User.query.filter_by(username=username).first_or_404()
  reviews = Review.query.filter_by(author=user)
  memes = Meme.query.filter_by(author=user)
  if user.role == "Admin":
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Staff Summary")
  else:
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Visitor Summary")


@reviews.route("/reviews/new", methods=["GET", "POST"])
@login_required
def new_review():
  if current_user.role != "Admin":
    abort(403)
  form = ReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
    review = Review(title=form.title.data, platform=form.platform.data, summary=form.summary.data,
                    content=form.content.data, author=current_user, thumbnail=picture_thumbnail)
    db.session.add(review)
    db.session.commit()
    flash(f"Your review has been submitted!", "success")
    return redirect(url_for("reviews.review_list"))
  return render_template("reviews/new_review.html", title="New Review", form=form, legend="GameBit Review")


@reviews.route("/reviews/rev-<int:review_id>/uploads", methods=["GET", "POST"])
@login_required
def picture_upload(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = PictureReviewForm()
  if form.validate_on_submit and "pictures" in request.files:
    for picture in request.files.getlist("pictures"):
      path = current_app.config["REVIEW_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_file = save_picture_all(picture, path, (1600, 900))
      picture = Picture(picture_file=picture_file, review_id=review_id)
      db.session.add(picture)
    db.session.commit()
    flash(f"Your pictures have been submitted!", "success")
    return redirect(url_for("reviews.full_review", review_id=review_id))
  return render_template("reviews/review_upload.html", form=form, title="Upload Pictures",
                         review=review, legend="Uploading pictures for: {}".format(review.title))


@reviews.route("/reviews/rev-<int:review_id>", methods=["GET", "POST"])
def full_review(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/full_review.html", title=review.title, review=review,
                         pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery", methods=["GET", "POST"])
def review_gallery(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/review_gallery.html", title="{} - gallery".format(review.title),
                         review=review, pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-thumbnail", methods=["GET", "POST"])
def full_thumbnail(review_id):
  review = Review.query.get_or_404(review_id)
  return render_template("reviews/full_thumbnail.html", title="Full picture", review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>", methods=["GET", "POST"])
def full_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  picture = Picture.query.get_or_404(picture_id)
  return render_template("reviews/full_picture.html", title="Full picture", picture=picture, review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>/delete", methods=["GET", "POST"])
def delete_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  picture = Picture.query.get_or_404(picture_id)
  path_rem = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
  db.session.delete(picture)
  try:
    if os.path.isfile(path_rem):
      os.remove(path_rem)
  except OSError as e:
    print("Error: {} : {}".format(path_rem, e.strerror))
  db.session.delete(picture)
  db.session.commit()
  flash('The picture has been deleted!', 'success')
  return redirect(url_for('reviews.review_gallery', review_id=review.id))


@reviews.route("/reviews/rev-<int:review_id>/list", methods=["GET", "POST"])
@login_required
def edit_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = UpdateReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path_rem = current_app.config["THUMBNAIL_PIC_PATH"]  + review.thumbnail
      try:
        if os.path.isfile(path_rem):
          os.remove(path_rem)
      except OSError as e:
        print("Error: {} : {}".format(path_rem, e.strerror))
        
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
      review.thumbnail = picture_thumbnail
    review.title = form.title.data
    review.platform = form.platform.data
    review.summary = form.summary.data
    review.content = form.content.data
    db.session.commit()
    flash(f"Your review has been updated!", "success")
    return redirect(url_for("reviews.full_review", review_id=review.id))
  elif request.method == "GET":
    form.title.data = review.title
    form.platform.data = review.platform
    form.summary.data = review.summary
    form.content.data = review.content
    form.thumbnail.data = review.thumbnail
  return render_template("reviews/edit_review.html", title="Editing: {}".format(review.title),
                         review=review, form=form, legend="Update the review")


@reviews.route("/reviews/rev-<int:review_id>/delete", methods=["GET", "POST"])
@login_required
def delete_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  pictures = Picture.query.filter_by(review_id=review_id)
  for picture in pictures:
    path = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
    db.session.delete(picture)
    try:
      if os.path.isfile(path):
        os.remove(path)
    except OSError as e:
      print("Error: {} : {}".format(current_app.config["REVIEW_PIC_PATH"], e.strerror))
  db.session.delete(review)
  db.session.commit()
  flash('The review has been deleted!', 'success')
  return redirect(url_for('reviews.review_list'))

gamebit/templates/home/about.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item active" aria-current="page">{{title}}</li>
{% endblock bread %}
<!--  -->
{% block body %}
<section class="jumbotron shadow cute_border">
    <article id="AboutTitle">
        <h1 class="display-4 text-center mb-4"><a href="{{url_for('main.home')}}">GameBit Council:</a></h1>
    </article>
    <article id="AboutInfo">
        <p>Welcome to our page where we are interested in providing a place for people to interact and talk about games they want to talk about. We also post our opinions on different games from a variety of platforms (Xbox, Playstation, PC, and other platforms)</p>
        <p>We first started as a <a href="https://www.facebook.com/GameBitCouncil/">Facebook page</a> and we have a decent, still a bit small, community that's growing everyday and that motivate us to keep going!
        </p>
        <p>This webpage will be focused just to the review part, in the Facebook page we do both, meme-ing around, but also reviewing and sharing our opinions with all of you.
        </p>
        <div class="alert alert-warning" role="alert">
            <p class="lead mb-0">We do not claim ownership on any of the pictures displayed in the webpage. All the credit goes to their respective artists.
            </p>
        </div>
        <div class="alert alert-danger" role="alert">
            <p class="lead mb-0">Regarding to memes, we try to keep them as respectful as possible, because, well, it's a meme.</p>
            <p class="text-center lead mb-0">To know more, check <a class="btn-link" href="{{url_for('main.rules')}}"><strong>the rules section</strong></a></p>
        </div>
        </p>
    </article>
    <article>
        <h3>GameBit Staff:</h3>
        <ul>
            {% for user in users %} {% if user.role == "Admin" %}
            <li>
                <a class="lead" href="{{url_for('reviews.user_review', username=user.username)}}">{{user.username}}</a>
            </li>
            {% endif %} {% endfor %}
        </ul>
    </article>
    <article id="SocialMedia">
        <h3>Social Media:</h3>
        <div class="d-flex justify-content-center">
            <a href="https://www.facebook.com/GameBitCouncil/"><i class="fab fa-facebook-square big_icon"></i></a>
        </div>
    </article>
</section>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/home/home.html
{% extends "base.html" %}
<!-- extended from -->
{% block body %}
<section class="jumbotron cuter_border shadow">
    <article id="PageSalute" class="text-center">
        <h1 class="display-4"><a href="https://www.facebook.com/GameBitCouncil/">GameBit Council</a></h1>
        <h2>Hello, world!</h2>
    </article>
    <hr class="my-4">
    <article id="PageInfo">
        <p class="lead">Welcome to our page where we are interested in providing a place for people to interact and talk about games they want to talk about. </p>
        <p class="lead">We also post our opinions on different games from a variety of platforms (Xbox, PlayStation, PC, and other platforms)</p>
    </article>
</section>
<section class="row row-cols-1 row-cols-md-2">
    <div class="col mb-3">
        <section id="Card1" class="card text-center cuter_border shadow  p-1">
            <figure class="mb-0">
                <img class="card-img-top cuter_border" src="{{url_for('static', filename='home_pictures/About us collage.jpg')}}" alt="GameBit Home">
            </figure>
            <article class="card-body">
                <h5 class="card-title">What's GameBit Council?</h5>
                <p class="card-text">Click the button down bellow to know a little bit more about us and who we are!</p>
                <a href="{{url_for('main.about')}}" class="btn btn-primary btn-block">About us</a>
            </article>
        </section>
    </div>
    <div class="col mb-3">
        <section id="Card2" class="card text-center cuter_border shadow p-1">
            <article id="carouselExampleSlidesOnly" class="carousel slide cuter_border" data-ride="carousel" data-interval="2000">
                <div class="carousel-inner">
                    <figure class="carousel-item active mb-0">
                        <img class="d-block w-100 cuter_border" src="{{url_for('static', filename='home_pictures/Review collage 1.jpg')}}" alt="First slide">
                    </figure>
                    <figure class="carousel-item mb-0">
                        <img class="d-block w-100 cuter_border" src="{{url_for('static', filename='home_pictures/Review collage 2.jpg')}}" alt="Second slide">
                    </figure>
                    <figure class="carousel-item mb-0">
                        <img class="d-block w-100 cuter_border" src="{{url_for('static', filename='home_pictures/Review collage 3.jpg')}}" alt="Third slide">
                    </figure>
                    <figure class="carousel-item mb-0">
                        <img class="d-block w-100 cuter_border" src="{{url_for('static', filename='home_pictures/Review collage 4.jpg')}}" alt="Fourth slide">
                    </figure>
                </div>
            </article>
            <article class="card-body">
                <h5 class="card-title">Reviews</h5>
                <p class="card-text">The game's we've reviewed so far. we'll be adding some more soon!</p>
                <a href="{{url_for('reviews.review_list')}}" class="btn btn-primary btn-block">Check our reviews</a>
            </article>
        </section>
    </div>
    <div class="col mb-3">
        <section id="Card3" class="card text-center cuter_border shadow  p-1">
            <figure class="mb-0">
                <img class="card-img-top cuter_border" src="{{url_for('static', filename='home_pictures/Memes collage 2.jpg')}}" alt="GameBit Home">
            </figure>
            <article class="card-body">
                <h5 class="card-title">Memes</h5>
                <p class="card-text">Having a rough day and you just wanna laugh? Head on to our memes section!</p>
                <a href="{{url_for('memes.meme_list')}}" class="btn btn-primary btn-block">Meme gallery</a>
            </article>
        </section>
    </div>
    {% if current_user.is_authenticated and current_user.role =="Admin" %}
    <div class="col mb-3">
        <section id="Card4" class="card text-center cuter_border shadow p-1">
            <figure class="mb-0">
                <img class="card-img-top cuter_border" src="{{url_for('static', filename='home_pictures/Collage for New.jpg')}}" alt="GameBit for New">
            </figure>
            <article class="card-body">
                <h5 class="card-title">Write a new Review!</h5>
                <p class="card-text">Type a new review for our list! Don't forget to double check if the game you're reviewing was reviewed already.</p>
                <a href="{{url_for('reviews.new_review')}}" class="btn btn-primary btn-block">New Review</a>
            </article>
        </section>
    </div>
    {% endif %}
    <div class="col mb-3">
        <section id="Card5" class="card text-center cuter_border shadow p-1">
            <figure class="mb-0">
                <img class="card-img-top cuter_border" src="{{url_for('static', filename='home_pictures/Memes collage.jpg')}}" alt="GameBit for New">
            </figure>
            <article class="card-body">
                {% if current_user.is_authenticated %}
                <h5 class="card-title">Post a new meme!</h5>
                <p class="card-text">Maybe you'll make someone laugh today with some nonsense, so go ahead!</p>
                <a href="{{url_for('memes.new_meme')}}" class="btn btn-primary btn-block">New Meme</a>
                <!---->
                {% else %}
                <h5 class="card-title">You gotta log in first</h5>
                <p class="card-text">Before interacting with the page, like, posting memes, you've to log in, don't forget!</p>
                <a href="{{url_for('users.login')}}" class="btn btn-primary btn-block">Log in</a>
                <!---->
                {% endif %}
            </article>
        </section>
    </div>
</section>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/home/rules.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('main.about')}}">About us</a></li>
<li class="breadcrumb-item active" aria-current="page">{{title}}</li>
{% endblock bread %}
<!--  -->
{% block body %}
<article class="alert alert-danger">
    <p class="mb-0 lead">As long as the rules are being followed there won't be any kind of issues. So please, <strong><em>keep that in mind</em></strong>.</p>
</article>
<section class="jumbotron shadow cute_border pt-5 pb-5">
    <article id="RulesTitle" style="background-color: var(--jumby);" class="pl-3 mb-4">
        <h1 class="display-4">GameBit Rules:</h1>
    </article>
    <article class="pl-2" id="RulesInfo">
        <ol class="mb-0 ">
            <li>Don't post anything that's blatantly offensive.</li>
            <li>Keep it <a class="btn-link" href="https://en.wiktionary.org/wiki/SFW#English"><strong><em>Safe For Work (SFW)</em></strong></a>, during the day. Lewds may be accepted at night.</li>
            <li>Try to keep memes without <strong><em>racism</em></strong> or <strong><em>heavy politics</em></strong> involved.</li>
            <li>We are a friendly place where everyone can share their opinion. So, <strong><em>keep the toxicity away</em></strong>.</li>
        </ol>
    </article>
</section>
<!-- Endblock -->
{% endblock body %}