gamebit/main/routes.py
from flask import Flask, Blueprint, render_template
from gamebit.models import User

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
  return render_template("home/home.html", title="Home")

@main.route("/about")
def about():
  users = User.query.all()
  return render_template("home/about.html", title="About us", users=users)

@main.route("/about/rules")
def rules():
  return render_template("home/rules.html", title="Rules")

gamebit/memes/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, flash, 
                   redirect, url_for, abort, current_app)
from gamebit.models import Meme
from flask_login import current_user
from gamebit import db
from gamebit.memes.forms import MemeForm
from gamebit.users.utils import save_picture_all

memes = Blueprint("memes", __name__)

#meme routes
@memes.route("/memes", methods=["GET", "POST"])
def meme_list():
  page = request.args.get("page", 1, type=int)
  memes = Meme.query.order_by(
      Meme.date_posted.desc()).paginate(page=page, per_page=10)
  return render_template("memes/meme_list.html", title="Memes", memes=memes)


@memes.route("/memes/mem-<meme_id>", methods=["GET", "POST"])
def full_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  return render_template("memes/full_meme.html", title="{}".format(meme.caption), meme=meme)


@memes.route("/memes/new", methods=["GET", "POST"])
def new_meme():
  if current_user.is_authenticated:
    form = MemeForm()
    if form.validate_on_submit():
      if form.meme.data:
        path = current_app.config["MEME_PATH"]
        try:
          if not os.path.exists(path):
            os.mkdir(path)
        except OSError:
          print("Couldn't create the directory {}".format(path))
        posted_meme = save_picture_all(form.meme.data, path, (1280, 720))
        meme = Meme(meme=posted_meme, caption=form.caption.data, author=current_user)
        db.session.add(meme)
      db.session.commit()
      flash(f"Your meme has been submitted!", "success")
      return redirect(url_for("memes.meme_list"))
  else:
    abort(403)
  return render_template("memes/new_meme.html", title="Upload a Meme", form=form, legend="Make someone laugh!")


@memes.route("/memes/delete/mem-<meme_id>", methods=["GET", "POST"])
def delete_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  if current_user == meme.author: 
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  elif current_user.role == "Admin":
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  else:
    abort(403)

gamebit/reviews/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, abort, flash, 
                   redirect, url_for, current_app)
from gamebit.models import Review, User, Meme, Picture
from flask_login import current_user, login_required
from gamebit import db
from gamebit.reviews.forms import ReviewForm, UpdateReviewForm, PictureReviewForm
from gamebit.users.utils import save_picture_all

reviews = Blueprint("reviews", __name__)

#Review routes
@reviews.route("/reviews")
def review_list():
  page = request.args.get("page", 1, type=int)
  reviews = Review.query.order_by(
      Review.date_posted.desc()).paginate(page=page, per_page=4)
  return render_template("reviews/review_list.html", title="Reviews", reviews=reviews)


@reviews.route("/reviews/summary/<string:username>")
def user_review(username):
  user = User.query.filter_by(username=username).first_or_404()
  reviews = Review.query.filter_by(author=user)
  memes = Meme.query.filter_by(author=user)
  if user.role == "Admin":
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Staff Summary")
  else:
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Visitor Summary")


@reviews.route("/reviews/new", methods=["GET", "POST"])
@login_required
def new_review():
  if current_user.role != "Admin":
    abort(403)
  form = ReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
    review = Review(title=form.title.data, platform=form.platform.data, summary=form.summary.data,
                    content=form.content.data, author=current_user, thumbnail=picture_thumbnail)
    db.session.add(review)
    db.session.commit()
    flash(f"Your review has been submitted!", "success")
    return redirect(url_for("reviews.review_list"))
  return render_template("reviews/new_review.html", title="New Review", form=form, legend="GameBit Review")


@reviews.route("/reviews/rev-<int:review_id>/uploads", methods=["GET", "POST"])
@login_required
def picture_upload(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = PictureReviewForm()
  if form.validate_on_submit and "pictures" in request.files:
    for picture in request.files.getlist("pictures"):
      path = current_app.config["REVIEW_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_file = save_picture_all(picture, path, (1600, 900))
      picture = Picture(picture_file=picture_file, review_id=review_id)
      db.session.add(picture)
    db.session.commit()
    flash(f"Your pictures have been submitted!", "success")
    return redirect(url_for("reviews.full_review", review_id=review_id))
  return render_template("reviews/review_upload.html", form=form, title="Upload Pictures",
                         review=review, legend="Uploading pictures for: {}".format(review.title))


@reviews.route("/reviews/rev-<int:review_id>", methods=["GET", "POST"])
def full_review(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/full_review.html", title=review.title, review=review,
                         pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery", methods=["GET", "POST"])
def review_gallery(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/review_gallery.html", title="{} - gallery".format(review.title),
                         review=review, pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-thumbnail", methods=["GET", "POST"])
def full_thumbnail(review_id):
  review = Review.query.get_or_404(review_id)
  return render_template("reviews/full_thumbnail.html", title="Full picture", review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>", methods=["GET", "POST"])
def full_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  picture = Picture.query.get_or_404(picture_id)
  return render_template("reviews/full_picture.html", title="Full picture", picture=picture, review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>/delete", methods=["GET", "POST"])
def delete_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  picture = Picture.query.get_or_404(picture_id)
  path_rem = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
  db.session.delete(picture)
  try:
    if os.path.isfile(path_rem):
      os.remove(path_rem)
  except OSError as e:
    print("Error: {} : {}".format(path_rem, e.strerror))
  db.session.delete(picture)
  db.session.commit()
  flash('The picture has been deleted!', 'success')
  return redirect(url_for('reviews.review_gallery', review_id=review.id))


@reviews.route("/reviews/rev-<int:review_id>/list", methods=["GET", "POST"])
@login_required
def edit_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = UpdateReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path_rem = current_app.config["THUMBNAIL_PIC_PATH"]  + review.thumbnail
      try:
        if os.path.isfile(path_rem):
          os.remove(path_rem)
      except OSError as e:
        print("Error: {} : {}".format(path_rem, e.strerror))
        
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
      review.thumbnail = picture_thumbnail
    review.title = form.title.data
    review.platform = form.platform.data
    review.summary = form.summary.data
    review.content = form.content.data
    db.session.commit()
    flash(f"Your review has been updated!", "success")
    return redirect(url_for("reviews.full_review", review_id=review.id))
  elif request.method == "GET":
    form.title.data = review.title
    form.platform.data = review.platform
    form.summary.data = review.summary
    form.content.data = review.content
    form.thumbnail.data = review.thumbnail
  return render_template("reviews/edit_review.html", title="Editing: {}".format(review.title),
                         review=review, form=form, legend="Update the review")


@reviews.route("/reviews/rev-<int:review_id>/delete", methods=["GET", "POST"])
@login_required
def delete_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  pictures = Picture.query.filter_by(review_id=review_id)
  for picture in pictures:
    path = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
    db.session.delete(picture)
    try:
      if os.path.isfile(path):
        os.remove(path)
    except OSError as e:
      print("Error: {} : {}".format(current_app.config["REVIEW_PIC_PATH"], e.strerror))
  db.session.delete(review)
  db.session.commit()
  flash('The review has been deleted!', 'success')
  return redirect(url_for('reviews.review_list'))

gamebit/users/routes.py
import os
from flask import (Flask, Blueprint, redirect, url_for, render_template, 
                   flash, abort, request, current_app)
from flask_login import current_user, login_user, logout_user, login_required
from gamebit.users.forms import (RegistrationForm, LoginForm, UserLoginForm, 
                                 UpdateAccountForm, RequestResetForm, ResetPasswordForm)
from gamebit.models import User, Review
from gamebit import bcrypt, db
from gamebit.users.utils import send_reset_email, save_picture_all

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(
        form.password.data).decode("utf-8")
    user = User(username=form.username.data,
                email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash(f"Account successfully created!", "success")
    return redirect(url_for('users.login'))
  return render_template("users/visitor_register.html", title="Register", form=form, legend="Register Page")


@users.route("/register/staff/4NbsBs-zKQASnZwfcp0YPPVPks5G5qNCeBXqNAQewU1HbyUCykcWpSv0sxqrPeuUwXKcn8ZsfjUqx4M_zEGUh1ifOKj4m4xR4cBQqZmMYWV9Vjf6BdlJmmt2qPC9z3rcL9mdyyxdn8L74f1vdnXyyP58LKLBTBm7", methods=["GET", "POST"])
def staff_register():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = RegistrationForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(
        form.password.data).decode("utf-8")
    user = User(username=form.username.data, role="Admin",
                email=form.email.data, password=hashed_password)
    db.session.add(user)
    db.session.commit()
    flash(f"Account successfully created!", "success")
    return redirect(url_for('users.login'))
  return render_template("users/staff_register.html", title="Staff Register", form=form, legend="Register Page")


@users.route("/login/email", methods=["GET", "POST"])
def login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = LoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get("next")
      flash(f"You've logged in successfully!", "success")
      return redirect(next_page) if next_page else redirect(url_for('main.home'))
    else:
      flash(f"Failed to log in. Please check the email and password.", "danger")
  return render_template("users/login.html", title="Login", form=form, legend="Login Page")


@users.route("/login/user", methods=["GET", "POST"])
def user_login():
  if current_user.is_authenticated:
    return redirect(url_for('main.home'))
  form = UserLoginForm()
  if form.validate_on_submit():
    user = User.query.filter_by(username=form.username.data).first()
    if user and bcrypt.check_password_hash(user.password, form.password.data):
      login_user(user, remember=form.remember.data)
      next_page = request.args.get("next")
      flash(f"You've logged in successfully!", "success")
      return redirect(next_page) if next_page else redirect(url_for('main.home'))
    else:
      flash(f"Failed to log in. Please check the username and password.", "danger")
  return render_template("users/user_login.html", title="Login", form=form, legend="Login Page")


@users.route("/logout")
def logout():
  logout_user()
  flash(f"You've successfully logged off!", "success")
  return redirect(url_for("main.home"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
  reviews = Review.query.filter_by(author=current_user)
  form = UpdateAccountForm()
  if form.validate_on_submit():
    if form.picture.data:
      path = current_app.config["PROFILE_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_file = save_picture_all(form.picture.data, path, (400, 225))
      current_user.profile_picture = picture_file
    current_user.username = form.username.data
    current_user.email = form.email.data
    db.session.commit()
    flash(f"Your account info has been updated", "success")
    return redirect(url_for("users.account"))
  elif request.method == "GET":
    form.username.data = current_user.username
    form.email.data = current_user.email
  return render_template("users/account.html", title="Account Info", form=form,
                         legend="Account Info", reviews=reviews)


@users.route("/account/<int:user_id>", methods=['GET', 'POST'])
@login_required
def delete_account(user_id):
  user = User.query.get_or_404(user_id)
  if user != current_user:
    abort(403)
  logout_user()
  path_rem = current_app.config["PROFILE_PIC_PATH"] + user.profile_picture
  try:
    if os.path.isfile(path_rem):
      os.remove(path_rem)
  except OSError as e:
    print("Error: {} : {}".format(path_rem, e.strerror))
  db.session.delete(user)
  db.session.commit()
  flash('The user has been deleted!', 'success')
  return redirect(url_for('main.home'))


@users.route("/login/reset", methods=["GET", "POST"])
def reset_request():
  if current_user.is_authenticated:
    return redirect(url_for("main.home"))
  form = RequestResetForm()
  if form.validate_on_submit():
    user = User.query.filter_by(email=form.email.data).first()
    send_reset_email(user)
    flash(f"An Email has been sent with instructions to reset your password.", "info")
    return redirect(url_for("users.login"))
  return render_template("users/reset_request.html", title="Reset Password",
                         form=form, legend="Password Reset")


@users.route("/login/reset/<token>", methods=["GET", "POST"])
def reset_token(token):
  if current_user.is_authenticated:
    return redirect(url_for("main.home"))
  user = User.verify_token(token)
  if user is None:
    flash(f"That's an invalid or expired token", "warning")
    return redirect(url_for("users.reset_request"))
  form = ResetPasswordForm()
  if form.validate_on_submit():
    hashed_password = bcrypt.generate_password_hash(
        form.password.data).decode("utf-8")
    user.password = hashed_password
    db.session.commit()
    flash(f"Your password has been updated!", "success")
    return redirect(url_for('users.login'))
  return render_template("users/reset_token.html", title="Reset Password",
                         form=form, legend="Password Reset")

gamebit/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/jpg" href="{{url_for('static', filename='logo.jpg')}}" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='/fontawesome/css/all.css')}}">
    <!-- bootstrap -->
    {% if title %}
    <title>GameBit Council - {{title}}</title>
    {% else %}
    <title>GameBit Council</title>
    {% endif %}
    <!-- endif -->
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a href="{{url_for('main.home')}}"><img class="small_pic" src="{{url_for('static', filename='logo.jpg')}}" alt="GameBit-Council Logo"></a>
                <a class="navbar-brand" href="{{url_for('main.home')}}">GameBit Council</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample03" aria-controls="navbarsExample03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarsExample03">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link mt-1" href="{{url_for('main.about')}}">About us</a>
                        <a class="nav-item nav-link mt-1" href="{{url_for('reviews.review_list')}}">Reviews</a>
                        <a class="nav-item nav-link mt-1" href="{{url_for('memes.meme_list')}}">Memes</a>
                        <div class="label_div" id="theme-change">
                            <input type="checkbox" class="checkbox" id="checkbox-theme">
                            <label for="checkbox-theme" class="label_check theme-change">
                                <i class="fas fa-moon"></i>
                                <i class="fas fa-sun"></i>
                                <span class="ball"></span>
                            </label>
                        </div>
                    </div>
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <!--  -->
                        {% if current_user.role == "Admin" %}
                        <a class="nav-item nav-link" href="{{url_for('reviews.new_review')}}">New Review</a>
                        <!--  -->
                        {% endif %}
                        <a class="nav-item nav-link" href="{{url_for('memes.new_meme')}}">New Meme</a>
                        <a class="nav-item nav-link" href="{{url_for('users.account')}}">Account <i class="fas fa-user"></i></a>
                        <a class="nav-item nav-link" href="{{url_for('users.logout')}}">Log out <i class="fas fa-sign-out-alt"></i></a>
                        <!-- -->
                        {% else %}
                        <a class="nav-item nav-link" href="{{url_for('users.login')}}">Log in <i class="fas fa-sign-in-alt"></i></a>
                        <a class="nav-item nav-link" href="{{url_for('users.register')}}">Register <i class="fas fa-user-plus"></i></a>
                        <!--  -->
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <nav class="fixed_top bg-dark navbar-dark" aria-label="breadcrumb">
            <div class="container">
                <ol class="mb-0 breadcrumb p-0 pb-1">
                    <li class="breadcrumb-item" aria-current="page"><a href="{{url_for('main.home')}}"><i class="fas fa-home"></i></a></li>
                    <!--  -->
                    {% block bread %}
                    <!--  -->
                    {% endblock bread %}
                </ol>
            </div>
        </nav>
    </header>
    <main role="main " class="container ">
        <div class="row ">
            <div class="col-md-12 ">
                {% with messages = get_flashed_messages(with_categories=true) %}
                <!-- Flash messages -->
                {% if messages %}
                <!-- start for -->
                {% for category, message in messages %}
                <div class="alert alert-{{ category }} ">
                    {{ message }}
                </div>
                {% endfor %}
                <!-- endfor -->
                {% endif %}
                <!-- endwith -->
                {% endwith %}
                <!-- block start -->
                {% block body %} {% endblock body %}
            </div>
        </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js " integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj " crossorigin="anonymous "></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js " integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo " crossorigin="anonymous "></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js " integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI " crossorigin="anonymous "></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/blazy/1.8.2/blazy.min.js "></script>
    <script>
        // lazy loading
        var bLazy = new Blazy({
            selector: 'img'
        });
    </script>
    <script>
        //determines if the user has a set theme
        function detectColorScheme() {
            var theme = "light"; //default to light

            //local storage is used to override OS theme settings
            if (localStorage.getItem("theme")) {
                if (localStorage.getItem("theme") == "dark") {
                    var theme = "dark";
                }
            } else if (!window.matchMedia) {
                //matchMedia method not supported
                return false;
            } else if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
                //OS theme setting detected as dark
                var theme = "dark";
            }

            //dark theme preferred, set document with a `data-theme` attribute
            if (theme == "dark") {
                document.documentElement.setAttribute("data-theme", "dark");
            }
        }
        detectColorScheme();

        //identify the toggle switch HTML element
        const toggleSwitch = document.querySelector('#theme-change input[type="checkbox"]');

        //function that changes the theme, and sets a localStorage variable to track the theme between page loads
        function switchTheme(e) {
            if (e.target.checked) {
                localStorage.setItem('theme', 'dark');
                document.documentElement.setAttribute('data-theme', 'dark');
                toggleSwitch.checked = true;
            } else {
                localStorage.setItem('theme', 'light');
                document.documentElement.setAttribute('data-theme', 'light');
                toggleSwitch.checked = false;
            }
        }

        //listener for changing themes
        toggleSwitch.addEventListener('change', switchTheme, false);

        //pre-check the dark-theme checkbox if dark-theme is set
        if (document.documentElement.getAttribute("data-theme") == "dark") {
            toggleSwitch.checked = true;
        }
    </script>
    <!-- script -->
    {% block script %}
    <!-- script -->
    {% endblock script%}
</body>

</html>