gamebit/reviews/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, ValidationError
from gamebit.models import User, Review

class ReviewForm(FlaskForm):
  title = StringField("Title of the Game",
                      validators=[DataRequired("You can't leave the review without a title."), Length(min=4)])
  platform = StringField("Platforms where the game's available",
                         validators=[DataRequired("You can't leave the game without knowing where you can play it."), Length(min=4)])
  summary = TextAreaField("Short description about the game, it's genre and stuff like that",
                          validators=[DataRequired("Don't forget to add a short description, so they know what's going on."), Length(min=10)])
  content = TextAreaField("Actual content of the review",
                          validators=[DataRequired("A review without a review? You can't leave this section empty"), Length(min=20)])
  thumbnail = FileField("Upload a thumbnail for the Review",
                        validators=[FileAllowed(["jpg", "png", "gif", "bitmap", "jpeg"])])
  submit = SubmitField("Post the Review")

  def validate_title(self, title):
    review = Review.query.filter_by(title=title.data).first()
    if review:
      raise ValidationError(
          "That game was already reviewed. Please check the review list or choose another game.")


class UpdateReviewForm(FlaskForm):
  title = StringField("Title of the Game",
                      validators=[DataRequired("You can't leave the review without a title."), Length(min=2)])
  platform = StringField("Platforms where the game's available",
                         validators=[DataRequired("In which platforms can you play it? You can't leave this section empty."), Length(min=3)])
  summary = TextAreaField("Short description about the game, it's genre and stuff like that",
                          validators=[DataRequired("Don't forget to add a short description, so they know what's going on."), Length(min=10)])
  content = TextAreaField("Actual content of the review", validators=[DataRequired(
      "A review without a review? You can't leave this section empty"), Length(min=20)])
  thumbnail = FileField("Upload a new thumbnail for the Review",
                        validators=[FileAllowed(["jpg", "png", "gif", "bitmap", "jpeg"])])
  submit = SubmitField("Save changes")


class PictureReviewForm(FlaskForm):
  pictures = FileField("Upload some pictures",
                       validators=[FileAllowed(["jpg", "png", "gif", "bitmap", "jpeg", "webp"], "Pictures Only!")])
  submit = SubmitField("Submit the pictures")

gamebit/memes/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, flash, 
                   redirect, url_for, abort, current_app)
from gamebit.models import Meme
from flask_login import current_user
from gamebit import db
from gamebit.memes.forms import MemeForm
from gamebit.users.utils import save_picture_all

memes = Blueprint("memes", __name__)

#meme routes
@memes.route("/memes", methods=["GET", "POST"])
def meme_list():
  page = request.args.get("page", 1, type=int)
  memes = Meme.query.order_by(
      Meme.date_posted.desc()).paginate(page=page, per_page=10)
  return render_template("memes/meme_list.html", title="Memes", memes=memes)


@memes.route("/memes/mem-<meme_id>", methods=["GET", "POST"])
def full_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  return render_template("memes/full_meme.html", title="{}".format(meme.caption), meme=meme)


@memes.route("/memes/new", methods=["GET", "POST"])
def new_meme():
  if current_user.is_authenticated:
    form = MemeForm()
    if form.validate_on_submit():
      if form.meme.data:
        path = current_app.config["MEME_PATH"]
        try:
          if not os.path.exists(path):
            os.mkdir(path)
        except OSError:
          print("Couldn't create the directory {}".format(path))
        posted_meme = save_picture_all(form.meme.data, path, (1280, 720))
        meme = Meme(meme=posted_meme, caption=form.caption.data, author=current_user)
        db.session.add(meme)
      db.session.commit()
      flash(f"Your meme has been submitted!", "success")
      return redirect(url_for("memes.meme_list"))
  else:
    abort(403)
  return render_template("memes/new_meme.html", title="Upload a Meme", form=form, legend="Make someone laugh!")


@memes.route("/memes/delete/mem-<meme_id>", methods=["GET", "POST"])
def delete_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  if current_user == meme.author: 
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  elif current_user.role == "Admin":
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  else:
    abort(403)

gamebit/reviews/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, abort, flash, 
                   redirect, url_for, current_app)
from gamebit.models import Review, User, Meme, Picture
from flask_login import current_user, login_required
from gamebit import db
from gamebit.reviews.forms import ReviewForm, UpdateReviewForm, PictureReviewForm
from gamebit.users.utils import save_picture_all

reviews = Blueprint("reviews", __name__)

#Review routes
@reviews.route("/reviews")
def review_list():
  page = request.args.get("page", 1, type=int)
  reviews = Review.query.order_by(
      Review.date_posted.desc()).paginate(page=page, per_page=4)
  return render_template("reviews/review_list.html", title="Reviews", reviews=reviews)


@reviews.route("/reviews/summary/<string:username>")
def user_review(username):
  user = User.query.filter_by(username=username).first_or_404()
  reviews = Review.query.filter_by(author=user)
  memes = Meme.query.filter_by(author=user)
  if user.role == "Admin":
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Staff Summary")
  else:
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Visitor Summary")


@reviews.route("/reviews/new", methods=["GET", "POST"])
@login_required
def new_review():
  if current_user.role != "Admin":
    abort(403)
  form = ReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
    review = Review(title=form.title.data, platform=form.platform.data, summary=form.summary.data,
                    content=form.content.data, author=current_user, thumbnail=picture_thumbnail)
    db.session.add(review)
    db.session.commit()
    flash(f"Your review has been submitted!", "success")
    return redirect(url_for("reviews.review_list"))
  return render_template("reviews/new_review.html", title="New Review", form=form, legend="GameBit Review")


@reviews.route("/reviews/rev-<int:review_id>/uploads", methods=["GET", "POST"])
@login_required
def picture_upload(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = PictureReviewForm()
  if form.validate_on_submit and "pictures" in request.files:
    for picture in request.files.getlist("pictures"):
      path = current_app.config["REVIEW_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_file = save_picture_all(picture, path, (1600, 900))
      picture = Picture(picture_file=picture_file, review_id=review_id)
      db.session.add(picture)
    db.session.commit()
    flash(f"Your pictures have been submitted!", "success")
    return redirect(url_for("reviews.full_review", review_id=review_id))
  return render_template("reviews/review_upload.html", form=form, title="Upload Pictures",
                         review=review, legend="Uploading pictures for: {}".format(review.title))


@reviews.route("/reviews/rev-<int:review_id>", methods=["GET", "POST"])
def full_review(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/full_review.html", title=review.title, review=review,
                         pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery", methods=["GET", "POST"])
def review_gallery(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/review_gallery.html", title="{} - gallery".format(review.title),
                         review=review, pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-thumbnail", methods=["GET", "POST"])
def full_thumbnail(review_id):
  review = Review.query.get_or_404(review_id)
  return render_template("reviews/full_thumbnail.html", title="Full picture", review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>", methods=["GET", "POST"])
def full_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  picture = Picture.query.get_or_404(picture_id)
  return render_template("reviews/full_picture.html", title="Full picture", picture=picture, review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>/delete", methods=["GET", "POST"])
def delete_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  picture = Picture.query.get_or_404(picture_id)
  path_rem = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
  db.session.delete(picture)
  try:
    if os.path.isfile(path_rem):
      os.remove(path_rem)
  except OSError as e:
    print("Error: {} : {}".format(path_rem, e.strerror))
  db.session.delete(picture)
  db.session.commit()
  flash('The picture has been deleted!', 'success')
  return redirect(url_for('reviews.review_gallery', review_id=review.id))


@reviews.route("/reviews/rev-<int:review_id>/list", methods=["GET", "POST"])
@login_required
def edit_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = UpdateReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path_rem = current_app.config["THUMBNAIL_PIC_PATH"]  + review.thumbnail
      try:
        if os.path.isfile(path_rem):
          os.remove(path_rem)
      except OSError as e:
        print("Error: {} : {}".format(path_rem, e.strerror))
        
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
      review.thumbnail = picture_thumbnail
    review.title = form.title.data
    review.platform = form.platform.data
    review.summary = form.summary.data
    review.content = form.content.data
    db.session.commit()
    flash(f"Your review has been updated!", "success")
    return redirect(url_for("reviews.full_review", review_id=review.id))
  elif request.method == "GET":
    form.title.data = review.title
    form.platform.data = review.platform
    form.summary.data = review.summary
    form.content.data = review.content
    form.thumbnail.data = review.thumbnail
  return render_template("reviews/edit_review.html", title="Editing: {}".format(review.title),
                         review=review, form=form, legend="Update the review")


@reviews.route("/reviews/rev-<int:review_id>/delete", methods=["GET", "POST"])
@login_required
def delete_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  pictures = Picture.query.filter_by(review_id=review_id)
  for picture in pictures:
    path = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
    db.session.delete(picture)
    try:
      if os.path.isfile(path):
        os.remove(path)
    except OSError as e:
      print("Error: {} : {}".format(current_app.config["REVIEW_PIC_PATH"], e.strerror))
  db.session.delete(review)
  db.session.commit()
  flash('The review has been deleted!', 'success')
  return redirect(url_for('reviews.review_list'))

gamebit/templates/reviews/full_picture.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_list')}}">Reviews</a></li>
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.full_review', review_id=review.id)}}">{{review.title}}</a></li>
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_gallery', review_id=review.id)}}">Gallery</a></li>
<li class="breadcrumb-item active" aria-current="page">Picture {{picture.id + 1}}</li>
{% endblock bread %}
<!--  -->
{% block body %}
<section class="container d-flex flex-column bigger_space">
    <article>
        <a class="btn btn-secondary btn-block" href="{{url_for('reviews.review_gallery', review_id=review.id)}}">Back to gallery</a>
    </article>
    <section class="alert alert-warning mt-3" role="alert">
        <p class="mb-0">Some pictures may look blurry and stretched when they're displayed in full screen, but that's due to the picture resolution. I apologize.</p>
        <p class="mb-0">We do not claim ownership on the picture displayed. All the credit goes to their respective artists.</p>
    </section>
    <figure class="cute_border_for_pictures p-2">
        <img class="cute_border_for_pictures w-100" src="{{ url_for('static', filename='/review_pictures/' + picture.picture_file) }}" alt="{{review.title}}">
        <!--  -->
        {% if review.author == current_user %}
        <button type="button" class="btn btn-danger mt-3 btn-block" data-toggle="modal" data-target="#deleteModal">Delete Picture</button>
        <!--  -->
        {% endif %}
    </figure>
</section>
<!-- start modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete the picture?</h5>
                <button id="x_symbol" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="lead">This can't be unmade, are you sure you wanna proceed?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('reviews.delete_picture', picture_id=picture.id, review_id=review.id)}}" method="POST">
                    <input class="btn btn-danger float-right" type="submit" value="Delete picture">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/reviews/full_review.html
{% extends "base.html" %}
<!-- extended from -->
<section id="bread">
    {% block bread %}
    <li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_list')}}">Reviews</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{title}}</li>
    {% if current_user.is_authenticated %}
    <!--  -->
    {% if review.author == current_user %}
    <li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.picture_upload', review_id=review.id)}}">Upload Pictures</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_gallery', review_id=review.id)}}">Gallery</a></li>
    {% else %}
    <li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_gallery', review_id=review.id)}}">Gallery</a></li>
    {% endif %}
    <!--  -->
    {% else %}
    <li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_gallery', review_id=review.id)}}">Gallery</a></li>
    {% endif %}
    <!--  -->
    {% endblock bread %}
</section>
{% block body %}
<section class="review_article p-3 mb-4 shadow">
    <article id="ReviewInfo" class="m-auto text-center bigger_space">
        <h1 class="article-title text-center ">
            <a href="{{ url_for('reviews.full_review', review_id=review.id)}}">{{ review.title }}</a>
        </h1>
        <h5 class="mb-1">Available for: </h5>
        <h3 class=""><a href="{{ url_for('reviews.full_review', review_id=review.id)}}">{{ review.platform }}</a></h3>
        <hr class="my-2 w-50">
    </article>
    <article id="Carrousel" class="d-flex justify-content-center">
        <div id="carouselExampleControls" class="carousel slide carou_size" data-ride="carousel" data-interval="4000">
            <div class="carousel-inner cuter_border shadow">
                <figure class="carousel-item active mb-0">
                    <img class="d-block w-100 cuter_border" src="{{url_for('static', filename='/thumbnail/' + review.thumbnail) }}" alt="...">
                </figure>
                <!-- for -->
                {% for picture in pictures %}
                <figure class="carousel-item mb-0">
                    <img class="d-block w-100 cuter_border" src="{{url_for('static', filename='/review_pictures/' + picture.picture_file) }}" alt="...">
                </figure>
                <!-- endfor -->
                {% endfor %}
            </div>
            <article class="d-flex justify-content-center mt-3">
                <a class="btn btn-primary btn-block" href="{{url_for('reviews.review_gallery', review_id=review.id)}}">Gallery</a>
            </article>
            <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </article>
    <article id="ReviewSummary">
        <hr class="my-2">
        <h4 class="jumbito spaces">General Info:</h4>
        <p class="spaces">{{review.summary}}</p>
    </article>
    <article id="ReviewContent">
        <hr class="my-2">
        <h4 class="jumbito spaces">Review:</h4>
        <p class="spaces">{{review.content}}</p>
    </article>
    <!--  -->
    {% if review.author == current_user %}
    <hr class="my-2">
    <article id="ManageButtons" class="d-flex justify-content-around flex_container">
        <a href="{{url_for('reviews.edit_review', review_id=review.id)}}" class="btn btn-primary btn-block w-25 mr-2 mt-0 flex_button">Update Review</a>
        <a href="{{url_for('reviews.picture_upload', review_id=review.id)}}" class="btn btn-success btn-block w-25 ml-2 mr-2 mt-0 flex_button">Upload Pictures</a>
        <button type="button" class="btn btn-danger btn-block w-25 ml-2 mt-0 flex_button" data-toggle="modal" data-target="#deleteModal">Delete Review</button>
    </article>
    {% endif %}
    <hr class="my-2">
    <section id="AuthorInfo" class="d-flex justify-content-start">
        <figure class="small_pic_container m-0">
            <a href="{{url_for('reviews.user_review', username=review.author.username)}}"><img class="small_profile_pic" src="{{url_for('static', filename='profile_pictures/'+ review.author.profile_picture)}}" alt="{{review.author.username}}"></a>
        </figure>
        <article id="ReviewFooter" class="margin_left">
            <hr class="my-2">
            <a href="{{url_for('reviews.user_review', username=review.author.username)}}" class="mr-2">{{review.author.username}}</a><i class="fas fa-signature"></i>
            <small class="text_muted">{{review.date_posted.strftime("%Y-%m-%d")}}</small>
            <br>
            <small class="text_muted">To check more of the author, click their picture</small>
            <hr class="my-2">
        </article>
    </section>
</section>
<!-- start modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete the review?</h5>
                <button id="x_symbol" type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
            </div>
            <div class="modal-body">
                <p class="lead">This can't be unmade, are you sure you wanna proceed?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('reviews.delete_review', review_id=review.id)}}" method="POST">
                    <input class="btn btn-danger float-right" type="submit" value="Delete review">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/reviews/review_gallery.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_list')}}">Reviews</a></li>
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.full_review', review_id=review.id)}}">{{review.title}}</a></li>
<li class="breadcrumb-item active" aria-current="page">Gallery</li>
{% endblock bread %}
<!--  -->
{% block body %}
<article class="alert alert-warning mt-3" role="alert">
    <p class="mb-0">Some pictures may look blurry and stretched when they're displayed, but that's due to the picture resolution. I apologize.</p>
    <p class="mb-0">We do not claim ownership on any of the pictures displayed. All the credit goes to their respective artists.</p>
</article>
<section class="d-flex flex-column">
    <article class="">
        <figure class="cute_border_for_pictures p-3 mt-3 shadow">
            <a href="{{ url_for('reviews.full_thumbnail', review_id=review.id) }}">
                <img class="cute_border_for_pictures w-100" src="{{ url_for('static', filename='/thumbnail/' + review.thumbnail) }}" alt="review.title">
            </a>
            <figcaption class="text-center">{{review.title}}</figcaption>
            <figcaption class="text-center">Click the picture to open in fullscreen</figcaption>
        </figure>
    </article>
    {% for picture in pictures %}
    <article class="">
        <figure class="cute_border_for_pictures p-3 mt-3 shadow">
            <a href="{{url_for('reviews.full_picture', picture_id=picture.id, review_id=review.id)}}">
                <img class="cute_border_for_pictures w-100" src="{{url_for('static', filename='/review_pictures/' + picture.picture_file) }}" alt="{{review.title}}">
            </a>
            <figcaption class="text-center">{{review.title}}</figcaption>
            <figcaption class="text-center">Click the picture to open in fullscreen</figcaption>
        </figure>
    </article>
    {% endfor %}
</section>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/reviews/review_list.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item active" aria-current="page">{{title}}</li>
{% endblock bread %}
<!--  -->
{% block body %}
<section class="jumbotron cuter_border shadow p-3">
    <article class="text-center">
        <h1 class="display-6">Reviews</h1>
        <p class="lead">Check out or latest reviewed games!</p>
    </article>
</section>
<!-- start if -->
{% for review in reviews.items %}
<!-- for -->
<section class="review_article p-3 shadow mb-4">
    <div class="d-flex">
        <figure class="profile_pic_container m-0">
            <a href="{{url_for('reviews.user_review', username=review.author.username)}}"><img class="small_profile_pic" src="{{url_for('static', filename='profile_pictures/'+ review.author.profile_picture)}}" alt="{{review.author.username}}"></a>
        </figure>
        <article class="margin_left">
            <hr style="margin-top: 0 !important;" class="my-2">
            <a href="{{url_for('reviews.user_review', username=review.author.username)}}" class="mr-2">{{review.author.username}}</a><i class="fas fa-signature"></i>
            <small class="text_muted">{{review.date_posted.strftime("%Y-%m-%d")}}</small>
            <br>
            <small class="text_muted">To check out the full review, click on the title</small>
            <hr class="my-2">
        </article>
    </div>
    <hr class="my-2">
    <article class="m-auto text-center">
        <h2 class="article-title"><a href="{{ url_for('reviews.full_review', review_id=review.id)}}">{{ review.title }}</a></h2>
        <hr class="my-2 w-50">
        <h5 class="mb-1">Available for: </h5>
        <h4 class="article-title"><a href="{{ url_for('reviews.full_review', review_id=review.id)}}">{{ review.platform }}</a></h4>
        <hr class="my-2 w-50">
    </article>
    <figure class="text-center thumbnail_container">
        <img class="cuter_border shadow thumbnail_picture carou_size" src="{{url_for('static', filename='/thumbnail/' + review.thumbnail) }}" alt="...">
    </figure>
    <article>
        <hr class="my-2">
        <h4 class="jumbito"> General Info:</h4>
        <p class="spaces">{{review.summary}}</p>
    </article>
</section>
{% endfor %}
<!-- endfor -->
<nav aria-label="Page Navigation">
    {% for page_num in reviews.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    <ul class="pagination justify-content-center">
        {% if page_num %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('reviews.review_list', page=1)}}">Back to start</a>
        </li>
        {% if reviews.page == page_num %}
        <li class="page-item active">
            <a class="page-link" href="{{url_for('reviews.review_list', page=page_num)}}">{{page_num}}</a>
        </li>
        <!--  -->
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('reviews.review_list', page=page_num)}}">{{page_num}}</a>
        </li>
        <!-- endif -->
        {% endif %}
        <!-- endif -->
        {% else %}
        <!-- endif -->
        <li>
            ...
        </li>
        {% endif %}
    </ul>
    <!-- endfor -->
    {% endfor %}
</nav>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/reviews/user_review.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('reviews.review_list')}}">Reviews</a></li>
<li class="breadcrumb-item active" aria-current="page">{{title}}</li>
{% endblock bread %}
<!--  -->
{% block body %}
<section class="content-section p-5 cute_border shadow">
    <div class="d-flex justify-content-center">
        <article id="UserInfo" class="">
            <img class="medium_picc mb-3 shadow" src="{{url_for('static', filename='profile_pictures/'+ user.profile_picture)}}" alt="{{user.username}}">
        </article>
    </div>
    <h2 class="account-heading text-center mb-3">Author: {{user.username}}</h2>
    <hr class="my-2"> {% if user.role == "Admin" %}
    <article id="ReviewsInfo" class="mt-3">
        <h3 class="account-heading mb-2">Reviews posted:</h3>
        {% for review in reviews %}
        <ul class="mb-3">
            <li class="mb-0"><a href="{{url_for('reviews.full_review', review_id=review.id)}}">{{review.title}}</a></li>
        </ul>
        {% endfor %}
    </article>
    {% endif %}
    <article>
        <h3 class="account-heading mb-3">Memes posted:</h3>
        {% for meme in memes %}
        <ul class="mb-0">
            <li class="mb-0"><a href="{{url_for('memes.full_meme', meme_id=meme.id)}}">{{meme.caption}}</a></li>
        </ul>
        {% endfor %}
    </article>
</section>

{% endblock body %}