gamebit/memes/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length

class MemeForm(FlaskForm):
  meme = FileField("Upload a meme",
                   validators=[FileAllowed(["jpg", "png", "gif", "bitmap", "jpeg", "webp"], "Pictures Only!")])
  caption = StringField("Write a caption for your meme",
                        validators=[DataRequired("You can't leave the meme without a caption."), Length(min=2)])
  submit = SubmitField("Submit the meme")

gamebit/main/routes.py
from flask import Flask, Blueprint, render_template
from gamebit.models import User

main = Blueprint("main", __name__)

@main.route("/")
@main.route("/home")
def home():
  return render_template("home/home.html", title="Home")

@main.route("/about")
def about():
  users = User.query.all()
  return render_template("home/about.html", title="About us", users=users)

@main.route("/about/rules")
def rules():
  return render_template("home/rules.html", title="Rules")

gamebit/memes/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, flash, 
                   redirect, url_for, abort, current_app)
from gamebit.models import Meme
from flask_login import current_user
from gamebit import db
from gamebit.memes.forms import MemeForm
from gamebit.users.utils import save_picture_all

memes = Blueprint("memes", __name__)

#meme routes
@memes.route("/memes", methods=["GET", "POST"])
def meme_list():
  page = request.args.get("page", 1, type=int)
  memes = Meme.query.order_by(
      Meme.date_posted.desc()).paginate(page=page, per_page=10)
  return render_template("memes/meme_list.html", title="Memes", memes=memes)


@memes.route("/memes/mem-<meme_id>", methods=["GET", "POST"])
def full_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  return render_template("memes/full_meme.html", title="{}".format(meme.caption), meme=meme)


@memes.route("/memes/new", methods=["GET", "POST"])
def new_meme():
  if current_user.is_authenticated:
    form = MemeForm()
    if form.validate_on_submit():
      if form.meme.data:
        path = current_app.config["MEME_PATH"]
        try:
          if not os.path.exists(path):
            os.mkdir(path)
        except OSError:
          print("Couldn't create the directory {}".format(path))
        posted_meme = save_picture_all(form.meme.data, path, (1280, 720))
        meme = Meme(meme=posted_meme, caption=form.caption.data, author=current_user)
        db.session.add(meme)
      db.session.commit()
      flash(f"Your meme has been submitted!", "success")
      return redirect(url_for("memes.meme_list"))
  else:
    abort(403)
  return render_template("memes/new_meme.html", title="Upload a Meme", form=form, legend="Make someone laugh!")


@memes.route("/memes/delete/mem-<meme_id>", methods=["GET", "POST"])
def delete_meme(meme_id):
  meme = Meme.query.get_or_404(meme_id)
  if current_user == meme.author: 
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  elif current_user.role == "Admin":
    path_rem = current_app.config["MEME_PATH"] + meme.meme
    try:
      if os.path.isfile(path_rem):
        os.remove(path_rem)
    except OSError as e:
      print("Error: {} : {}".format(path_rem, e.strerror))
    db.session.delete(meme)
    db.session.commit()
    flash('The picture has been deleted!', 'success')
    return redirect(url_for('memes.meme_list'))
  else:
    abort(403)

gamebit/reviews/routes.py
import os
from flask import (Flask, Blueprint, request, render_template, abort, flash, 
                   redirect, url_for, current_app)
from gamebit.models import Review, User, Meme, Picture
from flask_login import current_user, login_required
from gamebit import db
from gamebit.reviews.forms import ReviewForm, UpdateReviewForm, PictureReviewForm
from gamebit.users.utils import save_picture_all

reviews = Blueprint("reviews", __name__)

#Review routes
@reviews.route("/reviews")
def review_list():
  page = request.args.get("page", 1, type=int)
  reviews = Review.query.order_by(
      Review.date_posted.desc()).paginate(page=page, per_page=4)
  return render_template("reviews/review_list.html", title="Reviews", reviews=reviews)


@reviews.route("/reviews/summary/<string:username>")
def user_review(username):
  user = User.query.filter_by(username=username).first_or_404()
  reviews = Review.query.filter_by(author=user)
  memes = Meme.query.filter_by(author=user)
  if user.role == "Admin":
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Staff Summary")
  else:
    return render_template("reviews/user_review.html", user=user, reviews=reviews,
                           memes=memes, title="Visitor Summary")


@reviews.route("/reviews/new", methods=["GET", "POST"])
@login_required
def new_review():
  if current_user.role != "Admin":
    abort(403)
  form = ReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
    review = Review(title=form.title.data, platform=form.platform.data, summary=form.summary.data,
                    content=form.content.data, author=current_user, thumbnail=picture_thumbnail)
    db.session.add(review)
    db.session.commit()
    flash(f"Your review has been submitted!", "success")
    return redirect(url_for("reviews.review_list"))
  return render_template("reviews/new_review.html", title="New Review", form=form, legend="GameBit Review")


@reviews.route("/reviews/rev-<int:review_id>/uploads", methods=["GET", "POST"])
@login_required
def picture_upload(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = PictureReviewForm()
  if form.validate_on_submit and "pictures" in request.files:
    for picture in request.files.getlist("pictures"):
      path = current_app.config["REVIEW_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_file = save_picture_all(picture, path, (1600, 900))
      picture = Picture(picture_file=picture_file, review_id=review_id)
      db.session.add(picture)
    db.session.commit()
    flash(f"Your pictures have been submitted!", "success")
    return redirect(url_for("reviews.full_review", review_id=review_id))
  return render_template("reviews/review_upload.html", form=form, title="Upload Pictures",
                         review=review, legend="Uploading pictures for: {}".format(review.title))


@reviews.route("/reviews/rev-<int:review_id>", methods=["GET", "POST"])
def full_review(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/full_review.html", title=review.title, review=review,
                         pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery", methods=["GET", "POST"])
def review_gallery(review_id):
  review = Review.query.get_or_404(review_id)
  pictures = Picture.query.filter_by(review_id=review_id)
  return render_template("reviews/review_gallery.html", title="{} - gallery".format(review.title),
                         review=review, pictures=pictures)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-thumbnail", methods=["GET", "POST"])
def full_thumbnail(review_id):
  review = Review.query.get_or_404(review_id)
  return render_template("reviews/full_thumbnail.html", title="Full picture", review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>", methods=["GET", "POST"])
def full_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  picture = Picture.query.get_or_404(picture_id)
  return render_template("reviews/full_picture.html", title="Full picture", picture=picture, review=review)


@reviews.route("/reviews/rev-<int:review_id>/gallery/pic-<int:picture_id>/delete", methods=["GET", "POST"])
def delete_picture(picture_id, review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  picture = Picture.query.get_or_404(picture_id)
  path_rem = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
  db.session.delete(picture)
  try:
    if os.path.isfile(path_rem):
      os.remove(path_rem)
  except OSError as e:
    print("Error: {} : {}".format(path_rem, e.strerror))
  db.session.delete(picture)
  db.session.commit()
  flash('The picture has been deleted!', 'success')
  return redirect(url_for('reviews.review_gallery', review_id=review.id))


@reviews.route("/reviews/rev-<int:review_id>/list", methods=["GET", "POST"])
@login_required
def edit_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  form = UpdateReviewForm()
  if form.validate_on_submit():
    if form.thumbnail.data:
      path_rem = current_app.config["THUMBNAIL_PIC_PATH"]  + review.thumbnail
      try:
        if os.path.isfile(path_rem):
          os.remove(path_rem)
      except OSError as e:
        print("Error: {} : {}".format(path_rem, e.strerror))
        
      path = current_app.config["THUMBNAIL_PIC_PATH"]
      try:
        if not os.path.exists(path):
          os.mkdir(path)
      except OSError:
        print("Couldn't create the directory {}".format(path))
      picture_thumbnail = save_picture_all(form.thumbnail.data, path, (1280, 720))
      review.thumbnail = picture_thumbnail
    review.title = form.title.data
    review.platform = form.platform.data
    review.summary = form.summary.data
    review.content = form.content.data
    db.session.commit()
    flash(f"Your review has been updated!", "success")
    return redirect(url_for("reviews.full_review", review_id=review.id))
  elif request.method == "GET":
    form.title.data = review.title
    form.platform.data = review.platform
    form.summary.data = review.summary
    form.content.data = review.content
    form.thumbnail.data = review.thumbnail
  return render_template("reviews/edit_review.html", title="Editing: {}".format(review.title),
                         review=review, form=form, legend="Update the review")


@reviews.route("/reviews/rev-<int:review_id>/delete", methods=["GET", "POST"])
@login_required
def delete_review(review_id):
  review = Review.query.get_or_404(review_id)
  if review.author != current_user and current_user.role != "Admin":
    abort(403)
  pictures = Picture.query.filter_by(review_id=review_id)
  for picture in pictures:
    path = current_app.config["REVIEW_PIC_PATH"] + picture.picture_file
    db.session.delete(picture)
    try:
      if os.path.isfile(path):
        os.remove(path)
    except OSError as e:
      print("Error: {} : {}".format(current_app.config["REVIEW_PIC_PATH"], e.strerror))
  db.session.delete(review)
  db.session.commit()
  flash('The review has been deleted!', 'success')
  return redirect(url_for('reviews.review_list'))

gamebit/templates/memes/full_meme.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('memes.meme_list')}}">Memes</a></li>
<li class="breadcrumb-item active" aria-current="page">Meme #{{meme.id}}</li>
{% endblock bread %}
<!--  -->
{% block body %}
<section class="container d-flex flex-column bigger_space">
    <article class="mb-3">
        <a class="btn btn-secondary btn-block" href="{{url_for('memes.meme_list')}}">Back to Memes</a>
    </article>
    <article class="alert alert-warning" role="alert">
        <p class="lead mb-0">Some pictures may look blurry and stretched when they're displayed in full screen, but that's due to the picture resolution. I apologize.</p>
    </article>
    <article class="cute_border_for_pictures p-2 mb-3">
        <figcaption class="text-center mb-2">{{meme.caption}}</figcaption>
        <figure class="d-flex justify-content-center">
            <img class="cuter_border w-75" src="{{url_for('static', filename='/memes/' + meme.meme) }}" alt="{{meme.caption}}">
        </figure>
        {% if meme.author == current_user or current_user.role == "Admin" %}
        <button type="button" class="btn btn-danger mt-3 btn-block" data-toggle="modal" data-target="#deleteModal">Delete Picture</button>
        <!--  -->
        {% endif %}
    </article>
</section>
<!-- start modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete the picture?</h5>
                <button id="x_symbol" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="lead">This can't be unmade, are you sure you wanna proceed?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('memes.delete_meme', meme_id=meme.id)}}" method="POST">
                    <input class="btn btn-danger float-right" type="submit" value="Delete picture">
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/memes/meme_list.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item active" aria-current="page">{{title}}</li>
{% if current_user.is_authenticated %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('memes.new_meme')}}">Upload a meme</a></li>
{% endif %} {% endblock bread %}
<!--  -->
{% block body %}
<section class="jumbotron cuter_border shadow p-3">
    <article class="text-center">
        <h1 class="display-6">Have a Laugh!</h1>
        <p class="lead">Why not relax a bit seeing memes? You can always read our reviews later.</p>
    </article>
</section>
<section class="row row-cols-1 row-cols-md-2">
    {% for meme in memes.items %}
    <div class="col mb-2">
        <div class="cute_border_for_pictures mb-3 p-2 shadow">
            <p class="text-center lead">{{meme.caption}}</p>
            <figure class="d-flex justify-content-center">
                <a class="" href="{{url_for('memes.full_meme', meme_id=meme.id)}}">
                    <img class="cuter_border w-100" src="{{url_for('static', filename='/memes/' + meme.meme) }}" alt="{{meme.caption}}">
                </a>
            </figure>
            <hr class="my-2">
            <div class="flex_article justify-content-start p-2">
                <a href="{{url_for('reviews.user_review', username=meme.author.username)}}">{{meme.author.username}}</a><i style="line-height: 1.5;" class="ml-1 fas fa-signature"></i>
                <article class="margin_left">
                    <small class="text_muted">{{meme.date_posted.strftime("%Y-%m-%d")}}</small>
                    <br>
                    <small class="text_muted">To check out the full meme, click on the picture</small>
                </article>
            </div>
        </div>
    </div>
    {% endfor %}
</section>
<!-- start modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Delete the picture?</h5>
                <button id="x_symbol" type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p class="lead">This can't be unmade, are you sure you wanna proceed?</p>
            </div>
            {% for meme in memes.items %}
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <form action="{{url_for('memes.delete_meme', meme_id=meme.id)}}" method="POST">
                    <input class="btn btn-danger float-right" type="submit" value="Delete picture">
                </form>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- endfor -->
<nav aria-label="Page Navigation">
    {% for page_num in memes.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    <ul class="pagination justify-content-center">
        {% if page_num %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('memes.meme_list', page=1)}}">Back to start</a>
        </li>
        {% if memes.page == page_num %}
        <li class="page-item active">
            <a class="page-link" href="{{url_for('memes.meme_list', page=page_num)}}">{{page_num}}</a>
        </li>
        <!--  -->
        {% else %}
        <li class="page-item">
            <a class="page-link" href="{{url_for('memes.meme_list', page=page_num)}}">{{page_num}}</a>
        </li>
        <!-- endif -->
        {% endif %}
        <!-- endif -->
        {% else %}
        <!-- endif -->
        <li>
            ...
        </li>
        {% endif %}
    </ul>
    <!-- endfor -->
    {% endfor %}
</nav>
<!-- Endblock -->
{% endblock body %}

gamebit/templates/memes/new_meme.html
{% extends "base.html" %}
<!-- extended from -->
{% block bread %}
<li class="breadcrumb-item" aria-current="page"><a href="{{url_for('memes.meme_list')}}">Memes</a></li>
<li class="breadcrumb-item active" aria-current="page">{{title}}</li>
{% endblock bread %} {% block body %}
<div class="alert alert-danger" role="alert">
    <p class="lead mb-0">Keep in mind, if a meme goes against our rules, it'll be deleted. Check the <a class=" btn-link" href="{{url_for('main.rules')}}">rule list</a>, so you'll be free of guilt
    </p>
</div>
<form id="regForm" class="review_article bigger_space" action="" method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <fieldset class="">
        <legend class="">{{legend}}</legend>
        <hr class="my-2 mb-3">
        <section id="MemeForm">
            <article class="form-group">
                {{ form.caption.label(class="form-control-label")}}
                <!--  -->
                {% if form.caption.errors %}
                <!--  -->
                {{ form.caption(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.caption.errors %}
                    <span>{{ error }}</span>
                    <!--  -->
                    {% endfor %}
                </div>
                {% else %}
                <div tabindex="1">
                    {{ form.caption(class="form-control form-control-lg")}}
                    <small class="form-text text_muted">The cation must be, at least 3 characters long.</small>
                </div>
                {% endif %}
            </article>
            <article id="Meme" class="form-group">
                {{ form.meme.label(class="form-control-label")}}
                <!--  -->
                {{ form.meme(class="form-control-file form-control-lg pl-0 pr-0")}}
                <!--  -->
                {% if form.meme.errors %}
                <!--  -->
                {% for error in form.meme.errors %}
                <span class="text-danger">{{ error }}</span><br>
                <!--  -->
                {% endfor %}
                <!--  -->
                {% endif %}
            </article>
            <article>
                {{ form.submit(class="btn btn-success btn-block", id="submitBtn") }}
            </article>
        </section>
    </fieldset>
</form>
<!-- Endblock -->
{% endblock body %}